*&---------------------------------------------------------------------*
*& Report ZRETURNSTOCK_MOCK.
*&---------------------------------------------------------------------*
REPORT ZRETURNSTOCK_MOCK.

INCLUDE ZRETURNSTOCK_MOCK_T01.
*INCLUDE ZRETURNSTOCKT01.
INCLUDE ZRETURNSTOCK_MOCK_C01.
*INCLUDE ZRETURNSTOCKC01.
INCLUDE ZRETURNSTOCK_MOCK_F00.
*INCLUDE ZRETURNSTOCKF00.
INCLUDE ZRETURNSTOCK_MOCK_F01.
*INCLUDE ZRETURNSTOCKF01.
INCLUDE ZRETURNSTOCK_MOCK_F02.
*INCLUDE ZRETURNSTOCKF02.
INCLUDE ZRETURNSTOCK_MOCK_F03.
*INCLUDE ZRETURNSTOCKF03.
INCLUDE ZRETURNSTOCK_MOCK_O01.
*INCLUDE ZRETURNSTOCKO01.
INCLUDE ZRETURNSTOCK_MOCK_I01.
*INCLUDE ZRETURNSTOCKI01.

START-OF-SELECTION.
  PERFORM main_program.
