*&---------------------------------------------------------------------*
*& Report ZRETURN_STOCK
*&---------------------------------------------------------------------*
REPORT ZRETR_EXCH.

INCLUDE ZPG_MM_RETURN_STOCKT01.
INCLUDE ZPG_MM_RETURN_STOCKC01.
INCLUDE ZPG_MM_RETURN_STOCKF00.
INCLUDE ZPG_MM_RETURN_STOCKF01.
INCLUDE ZPG_MM_RETURN_STOCKF02.
INCLUDE ZPG_MM_RETURN_STOCKF03.
INCLUDE ZPG_MM_RETURN_STOCKO01.
INCLUDE ZPG_MM_RETURN_STOCKI01.

START-OF-SELECTION.
  PERFORM main_program.
