*&---------------------------------------------------------------------*
*& Report ZRETURN_STOCK
*&---------------------------------------------------------------------*
REPORT ZPG_MM_EXCHANGE_MATERIAL.

INCLUDE ZPG_MM_EXCHANGE_MATERIALT01.
INCLUDE ZPG_MM_EXCHANGE_MATERIALC01.
INCLUDE ZPG_MM_EXCHANGE_MATERIALF00.
INCLUDE ZPG_MM_EXCHANGE_MATERIALF01.
INCLUDE ZPG_MM_EXCHANGE_MATERIALF02.
INCLUDE ZPG_MM_EXCHANGE_MATERIALF03.
INCLUDE ZPG_MM_EXCHANGE_MATERIALO01.
INCLUDE ZPG_MM_EXCHANGE_MATERIALI01.

START-OF-SELECTION.
  PERFORM main_program.
